### PR TITLE
Update 0000-03-01-sudesna-chakraborty.md

### PR DESCRIPTION
**Pull request by sudesnac**
## Proposed changes

Describe the changes implemented in this pull request. If the changes fix a bug 
or resolves a feature request, be sure to link the issue. Please explain the 
issue and how the changes address the issue.

### CODE REVIEW

**Comment by kaitj** [comment]
lgtm - i noticed the image is stretching the border a little bit and am going to be patching this by enforcing the image size. This might cause your image to stretch when that is pushed!

**Review by kaitj — APPROVED** [review]

**Comment by sudesnac** [comment]
yea - just noticed the image is stretched in preview let me know if you want me to re-upload the image.

**Comment by kaitj** [comment]
> yea - just noticed the image is stretched in preview let me know if you want me to re-upload the image.

It should be okay - maybe take another look once the patch gets merged in and you can see if you want to reupload!

**Comment by kaitj** [comment]
This is what it would look like now that it enforces the image size (not sure if the preview will redeploy since the changes were made on a different branch). 

image

**Pull request merged**
